[package]
name = "noir_dl"
type = "bin"
authors = [""]

[dependencies]
bignum = {tag = "v0.5.0", git = "https://github.com/noir-lang/noir-bignum"}
sort = {tag = "v0.2.0", git = "https://github.com/noir-lang/noir_sort"}