[package]
name = "noir_dl"
type = "bin"
authors = [""]

[dependencies]
sort = {tag = "v0.2.0", git = "https://github.com/noir-lang/noir_sort"}
ripemd160 = { tag = "v0.0.2", git = "https://github.com/distributed-lab/noir-ripemd160" }